name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: تحميل المشروع
      uses: actions/checkout@v4

    - name: إعداد بايثون
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: تثبيت المتطلبات
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: إنشاء buildozer.spec
      run: |
        buildozer init
        sed -i 's/package.name = myapp/package.name = مهام/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = org.mahami/' buildozer.spec

    - name: بناء APK
      run: |
        buildozer -v android debug

    - name: حفظ APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
